version: '3.8'

# docker network connect dcas-0_dcasnet dcas-001_artisan_run_c5140be0da4e
services:
  #  edgerouter:
  #    image: traefik:v2.5
  #    command: --api.insecure=true --providers.docker
  #    ports:
  #      # The HTTP port
  #      - "8081:80"
  #      # The Web UI (enabled by --api.insecure=true)
  #      - "8080:8080"
  #  git:
  #    image: alpine/git:latest
  #    working_dir: /var/www/html
  #    volumes:
  #      - "../../:/var/www/html"
  #    networks:
  #      dcasnet:
  #        ipv4_address: 172.16.238.50
  #  testing:
  #    image: kirschbaumdevelopment/laravel-test-runner:8.0
  #    working_dir: /var/www/html
  #    volumes:
  #      - "../../:/var/www/html"
  #    networks:
  #      - defnet0
  artisan:
    build:
      context: .
      dockerfile: ./php8.dockerfile
    volumes:
      - "../../:/var/www/html"
    entrypoint: [ "php", "/var/www/html/artisan" ]
    working_dir: /var/www/html
#    networks:
#      - dcasnet
  composer:
    container_name: composer.dcas.local
    build:
      context: .
      dockerfile: ./composer.dockerfile
    volumes:
      - ../../:/var/www/html
    working_dir: /var/www/html
  npm:
    image: node:current-alpine
    volumes:
      - "../../:/var/www/html"
    entrypoint: [ "npm" ]
    working_dir: /var/www/html
  web:
    container_name: web.dcas.local
    image: nginx:latest
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/etc/ssl:/etc/ssl"
      - "../../:/var/www/html"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=web.dcas.local
    links:
      - redis
      - php
      - mysql
      - memcached
      - mailhog
    networks:
      - dcasnet
    restart: always
    depends_on:
      - php
      - mysql
  php:
    container_name: php.dcas.local
    build:
      context: .
      dockerfile: ./php8.dockerfile
    restart: always
    volumes:
      - "../../:/var/www/html"
    ports:
      - "9090:9000"
    networks:
      - dcasnet
  mysql:
    container_name: mysql.dcas.local
    image: mysql:latest
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=dcas_l8
      - MYSQL_ROOT_PASSWORD={KtE4^}E2*7)S_x2
      - MYSQL_USER=dcas
      - MYSQL_PASSWORD=Polycom600@@
    ports:
      - "3307:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    networks:
      - dcasnet
  redis:
    container_name: redis.dcas.local
    image: redis:6.2.5-alpine
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redis
    networks:
      - dcasnet
    depends_on:
      - mysql
    restart: unless-stopped
  memcached:
    container_name: cache.dcas.local
    image: bitnami/memcached:latest
    ports:
      - "11212:11211"
    environment:
      - MEMCACHED_USERNAME=memcached
      - MEMCACHED_PASSWORD=Polycom600@@
    networks:
      - dcasnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ../../search-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - dcasnet
    restart: unless-stopped
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - dcasnet
    restart: unless-stopped
    depends_on:
      - elasticsearch
  mailhog:
    container_name: mailhog.dcas.local
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - dcasnet
    restart: unless-stopped
networks:
  dcasnet:
    driver: bridge
volumes:
  elasticsearch-data:
    driver: local
