#
# @todo Still working out PHP problem with Nginx &
# @todo fluentd is still being worked on.
#

version: '3'

services:
  composer:
    container_name: composer.dcas.local
    build:
      context: .
      dockerfile: ./composer.dockerfile
    volumes:
      - ../../:/var/www/html
    working_dir: /var/www/html
  #  elasticsearch:
  #    container_name: search.dcas.local
  #      image: elasticsearch:7.14.1
  #    ports:
  #      - "9200:9200"
  #    volumes:
  #      - ../../search-data:/usr/share/elasticsearch/data
  #    networks:
  #      - dcasnet
  #    restart: unless-stopped
  #  fluentd:
  #    container_name: fluent.dcas.local
  #    build:
  #      context: .
  #      dockerfile: ./fluentd-logging.dockerfile
  #    ports:
  #      - "24224:24224"
  #    volumes:
  #      - ./fluentd/fluent.conf:/fluentd/etc/
  #    networks:
  #      - dcasnet
  #    restart: unless-stopped
  mailhog:
    container_name: mailhog.dcas.local
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - dcasnet
    restart: unless-stopped
  #  node:
  #    container_name: node.dcas.local
  #    build:
  #      context: .
  #      dockerfile: ./node.dockerfile
  #    user: "node"
  #    working_dir: /home/node/app
  #    environment:
  #      - NODE_ENV=production
  #    volumes:
  #      - ../../nodejs:/home/node/app
  #    expose:
  #      - "8081"
  #    command: "npm start"
  #    networks:
  #      - dcasnet
  #    restart: unless-stopped
  redis:
    container_name: redis.dcas.local
    image: redis:6.2.5-alpine
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redis
    networks:
      - dcasnet
    depends_on:
      - mysql
    restart: unless-stopped
  web:
    container_name: web.dcas.local
    image: nginx:latest
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/etc/ssl:/etc/ssl"
      - "../../:/var/www/html"
    ports:
      - "8080:80"
      - "3000:443"
    environment:
      - NGINX_HOST=web.dcas.local
    networks:
      - dcasnet
    restart: always
    depends_on:
      - php
      - mysql
  php:
    container_name: php.dcas.local
    image: php:8.1.0RC3-fpm-alpine
    restart: always
    volumes:
      - "../../:/var/www/html"
    ports:
      - "9090:9000"
    networks:
      - dcasnet
  mysql:
    container_name: mysql.dcas.local
    image: mysql:latest
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=dcas_l8
      - MYSQL_ROOT_PASSWORD={KtE4^}E2*7)S_x2
      - MYSQL_USER=dcas
      - MYSQL_PASSWORD=Polycom600@@
    ports:
      - "3307:3306"
    networks:
      - dcasnet
    volumes:
      - "./mysql:/var/lib/mysql"
  memcached:
    container_name: cache.dcas.local
    image: memcached:latest
    ports:
      - "11212:11211"
    networks:
      - dcasnet
networks:
  dcasnet:
    driver: bridge
