name: Branch Name
on:
  pull_request:
    types: [ opened ]
jobs:
  branch_name:
    runs-on: ubuntu-latest
    name: Branch Name
    steps:
      - uses: AlbertHernandez/branch-name-action@v1
        with:
          branch_pattern: 'feature|bug|chore|hotfix'
          comment_for_invalid_branch_name: 'Oops! This branch name is not following the standards! You can see them here: https://github.com/AlbertHernandez'
          fail_if_invalid_branch_name: 'true'
          ignore_branch_pattern: 'master|beta'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
